version: '3.1'

services:

  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: assignments
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass


  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis/data:/data

  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    restart: always
    ports:
      - 8080:80

