# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 13:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kitchen', 'kitchen'), ('client', 'client')], max_length=10, verbose_name='Тип чека')),
                ('order', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Информация о заказе')),
                ('status', models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], max_length=10, verbose_name='Статус чека')),
                ('pdf_file', models.FileField(upload_to='', verbose_name='Cсылка на PDF-файл')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Точка продажы',
                'verbose_name_plural': 'Точки продажи',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('api_key', models.CharField(max_length=100, unique=True, verbose_name='Ключ доступа к API')),
                ('check_type', models.CharField(choices=[('kitchen', 'kitchen'), ('client', 'client')], max_length=10, verbose_name='Тип печатаемого чека')),
                ('point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Point', verbose_name='Привязанная точка')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.AddField(
            model_name='check',
            name='printer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Printer', verbose_name='Принтер'),
        ),
    ]
