# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='', verbose_name='Cсылка на PDF-файл'),
        ),
    ]
