# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20191210_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='printer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='commerce.Printer', verbose_name='Принтер'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='point_id',
            field=models.IntegerField(verbose_name='Привязанная точка'),
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
